# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PUBLISH_PATH: '.'
  DEPLOY_PATH: 'www.core.somee.com'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core 8.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build App
      run: dotnet build --no-restore
    - name: Test App
      run: dotnet test --no-build --verbosity normal
    - name: Publish App
      run: dotnet publish --configuration Release -o '${{env.PUBLISH_PATH}}/Publish'
    - name: Deploy App using FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: core.somee.com
        username: KirtiShrw
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: '${{env.PUBLISH_PATH}}/Publish/'
        server-dir: '${{env.DEPLOY_PATH}}/'
        log-level: standard
        # dry-run: true      
